# Generated by Django 4.0.1 on 2022-03-12 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('java', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentarticle',
            name='email',
            field=models.EmailField(max_length=80, null=True),
        ),
    ]
