# Generated by Django 4.0.1 on 2022-03-12 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('java', '0002_commentarticle_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentarticle',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='java.commentarticle'),
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='commentarticle',
            name='body',
            field=models.TextField(null=True),
        ),
    ]
