# Generated by Django 4.0.1 on 2022-03-12 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('java', '0003_commentarticle_active_commentarticle_parent_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='java.commentarticle'),
        ),
    ]
