# Generated by Django 4.0.1 on 2022-03-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('java', '0004_alter_commentarticle_parent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
