# Generated by Django 4.0.1 on 2022-03-13 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('java', '0005_alter_commentarticle_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentArticle',
            new_name='CommentJava',
        ),
    ]
