# Generated by Django 4.0.1 on 2022-03-05 15:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbasic', '0005_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='name',
            new_name='author',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='active',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='email',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='updated',
        ),
    ]
