# Generated by Django 4.0.1 on 2022-03-05 16:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbasic', '0006_rename_name_comment_author_remove_comment_active_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comment',
            new_name='CommentArticle',
        ),
    ]
