# Generated by Django 4.0.1 on 2022-03-12 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbasic', '0007_rename_comment_commentarticle'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentarticle',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='pythonbasic.commentarticle'),
        ),
        migrations.AddField(
            model_name='commentarticle',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
