# Generated by Django 4.0.1 on 2022-03-12 19:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbasic', '0008_commentarticle_active_commentarticle_parent_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentarticle',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
