# Generated by Django 4.0.1 on 2022-03-13 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pythonbasic', '0011_alter_commentarticle_body'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CommentArticle',
            new_name='CommentPython',
        ),
    ]
