# Generated by Django 4.0.1 on 2022-03-09 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
