# Generated by Django 4.0.1 on 2022-03-09 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0002_alter_commentarticle_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='body',
            field=models.TextField(blank=True),
        ),
    ]
