# Generated by Django 4.0.1 on 2022-03-09 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0003_alter_commentarticle_body'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentarticle',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
