# Generated by Django 4.0.1 on 2022-03-12 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('android', '0005_androidarticle_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='androidarticle',
            name='category',
        ),
    ]
