# Generated by Django 4.0.1 on 2022-01-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Books',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('author', models.CharField(blank=True, max_length=255, null=True)),
                ('download', models.URLField(blank=True, max_length=1000, null=True)),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
