# Generated by Django 4.0.1 on 2022-01-20 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_books'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
